# Generated by Django 4.2.9 on 2024-03-17 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor_app', '0002_mydatetesting_dataset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mydatetesting',
            name='my_date',
            field=models.DateField(auto_now=True),
        ),
    ]
