# Generated by Django 4.2.9 on 2024-03-17 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predictor_app', '0003_alter_mydatetesting_my_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyDateTesting',
        ),
    ]
